[package]
name = "minecraft_clone"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13", features = ["wayland"] }
#NOTE: Disabling bevy/dynamic_linking may improve the performance of this linker (mold).
bevy_flycam = { version = "*" }
bevy_editor_pls = { version = "*" }
rand = { version = "*" }
strum = { version = "*", features = ["derive"] }


# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
